- name: installing SQL by mariadb
  apt:  
    name:
      - mariadb-server
      - python3-pymysql
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Enable the mariadb
  systemd: 
      name: mariadb
      enabled: yes

