
  - name: installing etcd
    apt:
      name:
          - etcd
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: enabling etcd
    systemd:
        name: etcd
        enabled: yes
